songs/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import SongListView, SongListViewSet

app_name = "songs_api"

router = DefaultRouter()
router.register(r'songsplaylist', SongListViewSet)

urlpatterns = [
    path('songs_list/', SongListView.as_view(), name='songs_list'),
    path('', include(router.urls)),
]

songs/urls.py
from django.urls import path

app_name = "songs"
urlpatterns = [

]

spotify/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import TemplateView




def bad(request):
    """ Simulates a server error """
    1 / 0


urlpatterns = [
    path("bad/", bad),
    path('', include('djvue.urls')),
    path(f"{settings.ADMIN_URL}/", admin.site.urls),
    
    path("user/", include("user.urls", namespace="user")),
    path("api/v1/", include("user.api.urls", namespace="user_api")),
    path("song/", include("songs.urls", namespace="songs")),
    path("api/v1/", include("songs.api.urls", namespace="songs_api")),
]

if settings.DEBUG:
    urlpatterns += [
        # Testing 404 and 500 error pages
        path("404/", TemplateView.as_view(template_name="404.html"), name="404"),
        path("500/", TemplateView.as_view(template_name="500.html"), name="500"),
    ]

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import RegisterView, MyObtainTokenPairView, UserListView

app_name = "user_api"


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('users/', UserListView.as_view(), name='users'),
    path('login/', MyObtainTokenPairView.as_view(), name='token_obtain_pair'),
    path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

user/urls.py
from django.urls import path

from .views import (
    UserDetailView,
    UserRedirectView,
    UserUpdateView,
    DashboardView,
    SignupView,
    LoginView
)

app_name = "user"
urlpatterns = [
    path("redirect/", view=UserRedirectView.as_view(), name="redirect"),
    path("dashboard/", view=DashboardView.as_view(), name="dashboard"),
    path("signup/", view=SignupView.as_view(), name="signup"),
    path("login/", view=LoginView.as_view(), name="login"),
    path("update/", view=UserUpdateView.as_view(), name="update"),
    path("<str:username>/", view=UserDetailView.as_view(), name="detail"),
]

songs/models.py
from django.db import models
from django_extensions.db.models import TitleDescriptionModel, ActivatorModel, TimeStampedModel

from user.models import User


# Create your models here.


class Songs(TitleDescriptionModel, TimeStampedModel, ActivatorModel):
    """
    model for the songs.
    """
    singer_name = models.CharField(max_length=25, null=True, blank=True)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='images/')


class SongPlaylist(TitleDescriptionModel, TimeStampedModel, ActivatorModel):
    """
    model for the user's song playlist.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='users')
    song = models.ManyToManyField(Songs)

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    def get_absolute_url(self):
        return reverse("user:detail", kwargs={"username": self.username})

user/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

songs/api/views.py
from rest_framework import viewsets
from rest_framework.generics import ListAPIView

from .serializers import SongSerializer, SongPlaylistSerializer
from ..models import Songs, SongPlaylist


class SongListView(ListAPIView):
    queryset = Songs.objects.all()
    serializer_class = SongSerializer


class SongListViewSet(viewsets.ModelViewSet):
    queryset = SongPlaylist.objects.all()
    serializer_class = SongPlaylistSerializer

songs/views.py
from django.shortcuts import render

# Create your views here.

user/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import generics
from rest_framework.generics import ListAPIView
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView

from .serializers import RegisterSerializer, MyTokenObtainPairSerializer, UserSerializer

User = get_user_model()


class RegisterView(generics.CreateAPIView):
    queryset = User.objects.none()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer


class MyObtainTokenPairView(TokenObtainPairView):
    permission_classes = (AllowAny,)
    serializer_class = MyTokenObtainPairSerializer


class UserListView(ListAPIView):
    queryset = User.objects.filter(is_active=True)
    serializer_class = UserSerializer

user/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView, TemplateView

User = get_user_model()


class DashboardView(TemplateView):
    template_name = 'dashboard.html'


class SignupView(TemplateView):
    template_name = 'signup.html'


class LoginView(TemplateView):
    template_name = 'login.html'


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("user:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("user:detail", kwargs={"username": self.request.user.username})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <title> spotify </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
            .main-body-class {
                background: black;
            }
            .navbar-brand img{
                height: 7rem;
            }
            a:hover {
              text-decoration: none!important;
            }
            .dedcription-btn {
              width: 10rem;
              position: relative;
              display: inline-block;
              border-radius: 30px;
              background-color: #fcfcfc;
              color: #008000;
              text-align: center;
              font-size: 18px;
              padding: 9px 0;
              transition: all 0.3s;
              padding-right: 40px;
              margin: 20px 5px;
              box-shadow: 0 3px 20px 0 rgba(0, 0, 0, 0.06);
            }
            .dedcription-btn .btn-icon {
              background-color: #008000;
              width: 75px;
              height: 45px;
              float: right;
              position: absolute;
              border-radius: 30px 30px 30px 0;;
              right: 0px;
              top: 0px;
              transition: all 0.3s;
            }
            .name-descripeion {
              position: relative;
              z-index: 9999;
              text-decoration: none;
            }
            .btn-icon::after {
              content: "";
              width: 0;
              height: 0;
              border-top: 45px solid #fcfcfc;
              border-right: 40px solid transparent;
              position: absolute;
              top: 0px;
              left: 0px;
            }
            .dedcription-btn:hover .btn-icon {
              width: 100%;
              border-radius: 30px;
            }
            .dedcription-btn:hover .btn-icon::after {
              display: none;
              opacity: 0.1;
            }
            .btn-icon i {
              position: absolute;
              right: 25px;
              top: 15px;
              color: #fff;
            }
            .dedcription-btn:hover {
              color: #fff!important;
            }
            .hover-box {
              display: flex;
              width: 100%;
              height: 100vh;
              justify-content: center;
              align-items: center;
            }
            .container-fluid .sign-up{
                border-radius: 10rem;
                height: 5rem;
                width: 11rem;
                margin-left: 65rem;
            }
            .container-fluid .login{
                border-radius: 10rem;
                height: 5rem;
                width: 11rem;
            }
            .navbar .container-fluid{
                padding-right: 10rem;
                padding-left: 10rem;
            }
            .container-fluid button span:after {
                  content: '\00bb';
                  position: absolute;
                  opacity: 0;
                  top: 0;
                  right: -20px;
                  transition: 0.5s;
                }

                .container-fluid button:hover span {
                  padding-right: 25px;
                }

                .container-fluid button:hover span:after {
                  opacity: 1;
                  right: 0;
                }
            .side-bar-class{
                width: 364px;
                height: 40rem;
            }
            .nav-pills .nav-link.active {
                color: #fff;
                background: #008000 !important;
                border-radius: 30px !important;
            }
            .side-bar-ul li:hover{
                color: #fff;
                background: #008000 !important;
                border-radius: 30px;
            }
            .btn-primary:hover,
.btn-primary:focus {
    background-color: #108d6f;
    border-color: #108d6f;
    box-shadow: none;
    outline: none;
}

.btn-primary {
    color: #fff;
    background-color: #007b5e;
    border-color: #007b5e;
}

section {
    padding: 60px 0;
}

section .section-title {
    text-align: center;
    color: #007b5e;
    margin-bottom: 50px;
    text-transform: uppercase;
}

#team .card {
    border: none;
    background: #ffffff;
}

.image-flip:hover .backside,
.image-flip.hover .backside {
    -webkit-transform: rotateY(0deg);
    -moz-transform: rotateY(0deg);
    -o-transform: rotateY(0deg);
    -ms-transform: rotateY(0deg);
    transform: rotateY(0deg);
    border-radius: .25rem;
}

.image-flip:hover .frontside,
.image-flip.hover .frontside {
    -webkit-transform: rotateY(180deg);
    -moz-transform: rotateY(180deg);
    -o-transform: rotateY(180deg);
    transform: rotateY(180deg);
}

.mainflip {
    -webkit-transition: 1s;
    -webkit-transform-style: preserve-3d;
    -ms-transition: 1s;
    -moz-transition: 1s;
    -moz-transform: perspective(1000px);
    -moz-transform-style: preserve-3d;
    -ms-transform-style: preserve-3d;
    transition: 1s;
    transform-style: preserve-3d;
    position: relative;
}

.frontside {
    position: relative;
    -webkit-transform: rotateY(0deg);
    -ms-transform: rotateY(0deg);
    z-index: 2;
    margin-bottom: 30px;
}

.backside {
    position: absolute;
    top: 0;
    left: 0;
    background: white;
    -webkit-transform: rotateY(-180deg);
    -moz-transform: rotateY(-180deg);
    -o-transform: rotateY(-180deg);
    -ms-transform: rotateY(-180deg);
    transform: rotateY(-180deg);
    -webkit-box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
    -moz-box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
    box-shadow: 5px 7px 9px -4px rgb(158, 158, 158);
}

.frontside,
.backside {
    -webkit-backface-visibility: hidden;
    -moz-backface-visibility: hidden;
    -ms-backface-visibility: hidden;
    backface-visibility: hidden;
    -webkit-transition: 1s;
    -webkit-transform-style: preserve-3d;
    -moz-transition: 1s;
    -moz-transform-style: preserve-3d;
    -o-transition: 1s;
    -o-transform-style: preserve-3d;
    -ms-transition: 1s;
    -ms-transform-style: preserve-3d;
    transition: 1s;
    transform-style: preserve-3d;
}

.frontside .card,
.backside .card {
    min-height: 312px;
}

.backside .card a {
    font-size: 18px;
    color: #007b5e !important;
}

.frontside .card .card-title,
.backside .card .card-title {
    color: #007b5e !important;
}

.frontside .card .card-body img {
    width: 120px;
    height: 120px;
    border-radius: 50%;
}
        </style>
        {# Global stylesheets #}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}

    </head>

    <body class="{% block body_class %}main-body-class{% endblock %}">

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

user/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% include 'header.html' %}
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="menu">
                <div class="d-flex flex-column flex-shrink-0 p-4 side-bar-class" style="width: 280px;" bis_skin_checked="1">
                <ul class="nav nav-pills flex-column mb-auto side-bar-ul">
                  <li class="nav-item">
                    <a href="#" class="nav-link active" aria-current="page">
                      <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                      Home
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link text-white">
                      <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                      PlayLists
                    </a>
                  </li>
                  <li>
                    <a href="#" class="nav-link text-white">
                      <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                      Favourite
                    </a>
                  </li>
                </ul>
                <hr>
                <div class="dropdown" bis_skin_checked="1">
                  <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                    <strong id="username"></strong>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
        <div class="col-sm-8">
        <div class="row songs-list">


        </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/header.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand"><img src="{% static 'images/Spotify-Logo.wine.svg' %}"></a>
      <a class="dedcription-btn" href="{% url 'user:signup' %}">
        <span class="name-descripeion">Sign Up</span>
        <div class="btn-icon">
          <i class="bi bi-box-arrow-in-right"></i>
        </div>
    </a>
  </div>
</nav>
{% endblock %}

user/templates/login.html
{% extends 'base.html' %}
{% block content %}
<!-- Section: Design Block -->
<section class="text-center text-lg-start">
  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Login up now</h2>
            <form method="post" id="login_form_id">
              <!-- 2 column grid layout with text inputs for the first and last names -->
              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="username_id" name="username" class="form-control" />
                    <label class="form-label" for="username_id">Username</label>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="password" id="password_id" name="password" class="form-control" />
                    <label class="form-label" for="password_id">Password</label>
                  </div>
                </div>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4">
                Login
              </button>
               <div class="text-center">
                <p>Don't have an account ? <a href="{% url 'user:signup' %}">SignUp</a></p>

              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->
{% endblock %}

user/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<!-- Section: Design Block -->
<section class="text-center text-lg-start">
  <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }
  </style>

  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Sign up now</h2>
            <form method="post" id="sign_form_id">
              {% csrf_token %}
              <!-- 2 column grid layout with text inputs for the first and last names -->
              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="first_name_id" name="first_name" class="form-control" />
                    <label class="form-label" for="first_name_id">First name</label>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="last_name_id" name="last_name" class="form-control" />
                    <label class="form-label" for="last_name_id">Last name</label>
                  </div>
                </div>
              </div>
               <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="username_id" name="username" class="form-control" />
                    <label class="form-label" for="username_id">Username</label>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="email" id="email_id" name="email" class="form-control" />
                    <label class="form-label" for="email_id">Email</label>
                  </div>
                </div>
              </div>

              <!-- Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="password_id" name="password" class="form-control" />
                <label class="form-label" for="password_id">Password</label>
              </div>

              <!-- Confirm Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="confirm_password_id" name="password2" class="form-control" />
                <label class="form-label" for="confirm_password_id">Confirm Password</label>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4" id="sign_up_id">
                Sign up
              </button>

              <!-- Register buttons -->
              <div class="text-center">
                <p>Already sign up ? <a href="{% url 'user:login' %}">Login</a></p>

              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->
{% endblock %}